<?php

function testimonial_upload_form_testimonial_node_form_alter(&$form,&$form_state){

        $form['title']['#title'] ='Testimonial Name';
        $form['options']['promote']['#value'] = 0;
        $form['ajax-submit']['#value'] = t('Submit');
        unset($form['ajax-submit']['#ajax']);
        $form['ajax-submit']['#submit'][] = 'testimonial_upload_form_submit';
}

function testimonial_upload_form_submit(&$form,&$form_state){

    $current_url = url(current_path(), array('absolute' => TRUE));
    $form_state['redirect'] = $current_url;
}





