<?php

//Alter the testimonial upload form from default behaviour
function testimonial_upload_form_testimonial_node_form_alter(&$form,&$form_state){

        $form['title']['#title'] ='Testimonial Name';
        $form['options']['promote']['#value'] = 0;
        $form['additional_settings']['#access'] = FALSE;
        $form['actions']['delete']['#access'] = FALSE;
        $form['options']['status']['#value'] =1;
        $form['#validate'][] = 'testimonial_upload_form_validation';
        $form['ajax-submit']['#value'] = t('Submit');
        unset($form['ajax-submit']['#ajax']);
        $form['ajax-submit']['#submit'][] = 'testimonial_upload_form_submit';
}

//validate the testimonial upload form
function testimonial_upload_form_validation(&$form,&$form_state){

    $description = $form_state['values']['field_testimonial_description']['und'][0]['value'];
    $length = strlen($description);
    if($length > 300){
        form_set_error('field_testimonial_description][und','Description field allows only 300 characters.');
   }
}

function testimonial_upload_form_submit(&$form,&$form_state){

    $current_url = url(current_path(), array('absolute' => TRUE));
    $form_state['redirect'] = $current_url;
}





