<?php

function e_catalogs_form_e_catalogs_node_form_alter(&$form, &$form_state, $form_id){
    $form['options']['promote']['#value'] = 0;
    $form['ajax-submit']['#submit'][] =  'e_catalogs_custom_submit';
    $form['additional_settings']['#access'] = FALSE;
    $form['actions']['delete']['#access'] = FALSE;
    $form['options']['status']['#value'] = 1;
    unset($form['ajax-submit']['#ajax']);

}

function e_catalogs_custom_submit($form,&$form_state){
    $current_url = url(current_path(), array('absolute' => TRUE));
    $form_state['redirect'] = 'partner/e-catalogs/upload/';
}

/**
 * View alter to display the file info for each file type for E-Catalogs nodes
 * @param $view
 *
 */

function e_catalogs_views_pre_render(&$view) {
    global $base_url;
    drupal_add_js($base_url.'/sites/all/modules/custom/e_catalogs/js/custom.js');
    // what needs to be done for each view
    switch($view->name){
        case 'e_catalogs_view':
            drupal_add_js($base_url.'/sites/all/modules/custom/e_catalogs/js/custom.js');
            break;
    }
}
