<?php

function e_catalogs_form_e_catalogs_node_form_alter(&$form, &$form_state, $form_id){
    $form['options']['promote']['#value'] = 0;
}

/**
 * View alter to display the file info for each file type for E-Catalogs nodes
 * @param $view
 *
 */

function e_catalogs_views_pre_render(&$view) {
    global $base_url;
    drupal_add_js($base_url.'/sites/all/modules/custom/e_catalogs/js/custom.js');
    // what needs to be done for each view
    switch($view->name){
        case 'e_catalogs_view':
            drupal_add_js($base_url.'/sites/all/modules/custom/e_catalogs/js/custom.js');
            break;
    }
}
