<?php

function make_a_request_form_webform_client_form_18724_alter( &$form, &$form_state, $form_id){

    $form_required_marker = array('#theme' => 'form_required_marker');
    $required = ' ' . drupal_render($form_required_marker);

    if($form_id == 'webform_client_form_18724'){
        $form['submitted']['request']['#title'] = t('Request:').$required;
    }

    $form['#validate'][] = 'make_a_request_form_validation';
}

function make_a_request_form_validation(&$form, &$form_state){

    $request = $form_state['values']['submitted']['request'];

    if(empty($request)){
        form_set_error('submitted][request','Please Enter your request');
    }
}



